chore(dependencies): update spmc dev dependency to 0.3  (#1913)
spmc 0.2.3 has been yanked on 2019-08-15

Passing to 0.2 requires a small change in the tests.
Changing the following (as was done in master branch)
  &'a spmc::Sender<Reply> -> &'a Mutex<spmc::Sender<Reply>>

This fixes the cargo issue telling us that he cannot handle smpc:
  error: failed to select a version for the requirement `spmc = "^0.2"`

Signed-off-by: Gabriel Ganne <gabriel.ganne@gmail.com>